### ISSUE TITLE
Missing project hirstory

### ISSUE THREAD

**Issue by tbeu** [undisputed-seraphim/libmatio#1]
Do you mind to add the complete git history of libmatio instead of single commit? You could e.g. fork from [telehan/libmatio](https://github.com/telehan/libmatio) or init again.

I have some PRs ready and there are also many of pathces at sf.net available.

**Comment by undisputed-seraphim** [comment]
Hm, I never knew I could clone from SF. I will fork from there shortly. Thanks for the heads up.
(Since that is a better idea I will delete this repo and reopen it again)

**Comment by undisputed-seraphim** [comment]
tbeu, I made a new repo that is a fork of SF. If you're interested, you can find it at https://github.com/undisputed-seraphim/matio

**Comment by tbeu** [comment]
:+1:
